[package]
name = "chamon-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
notify = "8.2.0"
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
tokio = "1.48.0"
ratatui-widgets = "0.3.0-alpha.5"
