[package]
name = "chamon-tui"
version = "0.1.0"
edition = "2021"

[lib]
name = "chamon_tui"
path = "src/lib.rs"

[[bin]]
name = "chamon"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
crossterm = "0.29.0"
md5 = "0.7"
notify = "8.2.0"
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
tachyonfx = "0.7"
tokio = "1.48.0"
ratatui-widgets = "0.3.0-alpha.5"
