
title_bar:
    display: "ChaMon - File Change Monitor (Watching)"
    background: "#FF0000"

commands_view:
    commands:
        - name: "Refresh Files [B]aseline"
          key: "b"
          desc: "Refresh baseline checksums of system files"
          command: "refresh"
        
        - name: "Show [D]ifferences"
          key: "d"
          desc: "Show git diff for selected file"
          command: "diff"
        
        - name: "[V]iew File"
          key: "v"
          desc: "Open file in default editor ($EDITOR or nano)"
          command: "view"
        
        - name: "[G]enerate Change Report"
          key: "g"
          desc: "Generate a detailed change report"
          command: "report"
        
        - name: "[T]rack File"
          key: "t"
          desc: "Add file to git tracking (git add)"
          command: "track"
        
        - name: "[U]ntrack File"
          key: "u"
          desc: "Remove file from git tracking (git rm --cached)"
          command: "untrack"

    
    
    
    
files_view:
    tab1:
        name: "Filtered"
    
    tab2:
        name: "All"


help_line:
    text: "↕ commands ←→ files [Q]uit [W]atch [H]elp [PgUp]/[PgDn]: Cycle between file views   "


    
    
    
    